server:
  port: 9002
  tomcat:
    threads:
      max: 10

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: Orchestration Services
    baseUrl: https://oh5vdeg59i.execute-api.eu-west-2.amazonaws.com
    version: 7.6.0
    authorize: https://launch.smarthealthit.org/v/r4/auth/authorize
    token: https://launch.smarthealthit.org/v/r4/auth/token
    introspect: https://launch.smarthealthit.org/v/r4/auth/introspect
    smart: true

###Remote terminology validation:

##Example without auth:
#terminology:
#  url: https://r4.ontoserver.csiro.au/fhir

##Example with auth:
#terminology:
#  url: https://ontology.nhs.uk/authoring/fhir/
#  authorization:
#    tokenUrl: https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token
#    clientId: test
#    clientSecret: test
